"""adiciona cpf, matricula e primeiro acesso

Revision ID: 323c19d3edd0
Revises: e4e58fa9a03b
Create Date: 2026-06-28 13:15:28.339515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323c19d3edd0'
down_revision = 'e4e58fa9a03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=False))
        batch_op.add_column(sa.Column('matricula', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('primeiro_acesso', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['matricula'])
        batch_op.create_unique_constraint(None, ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('primeiro_acesso')
        batch_op.drop_column('matricula')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
