"""criacao inicial

Revision ID: 76dd24969365
Revises: 
Create Date: 2026-06-17 20:51:00.755433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76dd24969365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('editora', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('quantidade_total', sa.Integer(), nullable=False),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=300), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emprestimo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.Date(), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('data_devolucao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo_livro', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('isbn'))

    op.drop_table('livros')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('usuarios')
    op.drop_table('emprestimos')
    op.drop_table('solicitacoes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('titulo_livro', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('autor', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('observacao', mysql.TEXT(), nullable=True),
    sa.Column('professor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('data_solicitacao', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], name=op.f('solicitacoes_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('emprestimos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('livro_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('data_emprestimo', sa.DATE(), nullable=False),
    sa.Column('data_prevista', sa.DATE(), nullable=False),
    sa.Column('data_devolucao', sa.DATE(), nullable=True),
    sa.Column('status', mysql.ENUM('ATIVO', 'DEVOLVIDO'), server_default=sa.text("'ATIVO'"), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], name=op.f('emprestimos_ibfk_2')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('emprestimos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('perfil', mysql.ENUM('ADMIN', 'PROFESSOR', 'ALUNO'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('livros',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('autor', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('editora', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ano', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantidade_total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantidade_disponivel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.CheckConstraint('`quantidade_disponivel` >= 0', name=op.f('check_qnt_disponivel')),
    sa.CheckConstraint('`quantidade_total` >= 0', name=op.f('check_qnt_total')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('isbn'), ['isbn'], unique=True)

    op.drop_table('solicitacao')
    op.drop_table('emprestimo')
    op.drop_table('usuario')
    op.drop_table('livro')
    # ### end Alembic commands ###
