"""add resumo e img de livros

Revision ID: cc0ad43e28ec
Revises: 1d6edb59c844
Create Date: 2026-06-29 21:59:29.653754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0ad43e28ec'
down_revision = '1d6edb59c844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imagem', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.drop_column('imagem')
        batch_op.drop_column('resumo')

    # ### end Alembic commands ###
