"""estrutura inicial

Revision ID: e4e58fa9a03b
Revises: 
Create Date: 2026-06-24 11:07:08.958487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e58fa9a03b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('editora', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('quantidade_total', sa.Integer(), nullable=False),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=300), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emprestimo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.Date(), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('data_devolucao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo_livro', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao')
    op.drop_table('emprestimo')
    op.drop_table('usuario')
    op.drop_table('livro')
    # ### end Alembic commands ###
